app/account/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/',views.login, name='login'),
    path('register/',views.register, name='register'),
    

]

app/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('',views.HomeView.as_view(), name="home"),
    path('lists/', views.MyListView.as_view(), name= "mylist"),

    path('createlist/', views.CreateList.as_view(), name = "create"),
    path('<int:pk>/deletelist/', views.DeleteList.as_view(), name = "delete"),
    path('updatelist/<int:pk>', views.UpdateList.as_view(), name = "update"),
    path('list_detail/<int:pk>', views.DetailList.as_view(), name="detail")
]

mysite/urls.py
from django import contrib
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('main.urls', namespace='main')),
    
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include('account.urls', namespace='accounts')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/account/models.py
from django.db import models

# Create your models here.

app/main/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class ToDoList(models.Model):
    name = models.CharField(max_length=100)
    
    def get_absolute_url(self):
        return reverse("main:detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.name


class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    complete = models.BooleanField()
    date=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text
    

app/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import fields

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class LoginForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1"]

app/main/forms.py
from django import forms

class CreateListForm(forms.Form):
    name = forms.CharField(label="Name", max_length=200)
    check = forms.BooleanField(required=False)

app/account/views.py
from typing import Generic
from django.http import response
from django.shortcuts import redirect, render
from .forms import RegisterForm, LoginForm

# Create your views here.
 
def register(response):
    
    if response.method == 'POST':
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
        return redirect("/accounts")
    else:
        form = RegisterForm()
    return render(response, "accounts/register.html", {"form": form})

def login(response):
    form = LoginForm(response.POST)
    return render(response, "registration/login.html", {"form": form})

app/main/views.py
# from .forms import CreateListForm
from .models import ToDoList
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.urls import reverse_lazy


# Create your views here.
class HomeView(TemplateView):
    template_name = 'main/home.html'

# To view the list of all Lists
class MyListView(ListView):
    template_name = 'main/mylist.html'
    context_object_name = 'list_name'
    
    def get_queryset(self):
        return ToDoList.objects.all()


class CreateList(CreateView):
    model = ToDoList
    fields = ['name']
    template_name = 'main/todolist_form.html'
     
class UpdateList(UpdateView):
    model = ToDoList
    fields = ['name']

class DeleteList(DeleteView):
    model = ToDoList
    success_url = reverse_lazy('main:home')


class DetailList(DetailView):
    model = ToDoList
    template_name = 'main/detail.html'
    context_object_name = 'list'
     
    

templates/accounts/register.html
{% extends 'main/home.html' %}
{% block content %}
{% load crispy_forms_tags %}

    <form action="" method="post" class="form-group">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-block btn-success">Register</button>
    </form>
    <p>Already registered? <a href="{% url 'accounts:login' %}">Login</a></p>
{% endblock %}

templates/main/detail.html
{% extends 'main/home.html' %}

{% block content %}

<div class="border border-success">
    <h5 class=" text-center">{{list.name}}</h5> 
    <ul class="list-group list-group-flush"></ul>
    {% for item in list.item_set.all %}
        {% if item.complete == True %}                      
            <li class="list-group-item"><input type="checkbox" value="clicked" checked>{{item.text}}</li><br>
        {% else %}
            <li class="list-group-item"><input type="checkbox" name="c{{item.id}}" value="clicked">{{item.text}}</li><br>
        {% endif %}
    {% endfor %}
    </ul>

    <div class="form-group mb-3 px-5">                            
        <a type="submit"  class="btn btn-lg btn-info btn-block" href="{% url 'main:update' list.id %}">Update</a>                                
    </div>


{% endblock %}

templates/main/form_template.html
{%  for field in form %}

    <div class="form-group">
        <div class="input-group  form-control my-5  justify-content-center border border-danger">
            <label class="col-sm-2">{{ field.label_tag }}</label>
            <div class="col-sm-10 mx-auto">{{ field }}</div>
        </div><hr>
    </div>

{% endfor %}

templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>To Do List</title>
</head>
<body>
    {% include 'main\navbar.html' %}
    
    <div id="content" name="content" class="main border border-danger ">
        <div class="col-md-8 m-auto border border-success p-0 ">
            <h1 class="mt-2 ml-4">My Site</h1>
            <hr class="mt-2 mb-4">

            {% block content %}
            {% endblock %}
        </div>
        
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html> 

templates/main/mylist.html
{% extends 'main/home.html' %}
{% block content %}
<!-- <div class="border border-secondary p-2 container"> -->
    
    {% for n in list_name %}

    {% if forloop.counter0|divisibleby:2 %} 

        <div class="card-deck border border-warning container m-auto p-0" > {%  endif %}

            <div class="card border border-danger">
              
                <div class="card-body border border-success">

                    <h5 class="card-title text-center">{{n.name}}</h5>
                    <ul class="list-group list-group-flush"></ul>
                    {% for i in n.item_set.all %}
                        {% if item.complete == True %}                      
                            <li class="list-group-item"><input type="checkbox" value="clicked" checked>{{i.text}}</li><br>
                        {% else %}
                            <li class="list-group-item"><input type="checkbox" name="c{{i.id}}" value="clicked">{{i.text}}</li><br>
                        {% endif %}
                    {% endfor %}
                    </ul>

                </div>
            </div> 
                
        
    {%  if forloop.counter|divisibleby:2 or forloop.last %} 
        </div><hr>
    
    {%  endif %}
    
    {% endfor %} 

    
                

    <div class="input-group block my-5  justify-content-center border border-danger">
        <input type="text" name="new" class="w-50" >
        <button type="submit" name="addItem" value="addItem" class="btn btn-primary block w-25">Add Item</button>
    </div><hr>
    
    <div class="input-group justify-content-center text-center border border-warning">
        <button type="submit" name="save" value="save" class="btn btn-block btn-success w-75" style="font-size: large;">Save</button>
    </div>
    
    
<!-- </div>  -->
{% endblock %}
    
   <!--  <form action="reverse('main:mylist')" method="post">
        {% csrf_token %}
        {% for name in list_name %}
            <h4>{{list_name.name}}</h4>
            <div>
                <h4 class="my-4">{{list_name.name}}</h4>
            {% for item in list_name.item_set.all %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        {% if item.complete == True %}
                        <input type="checkbox" name="c{{item.id}}" value="clicked" checked>
                        {% else %}
                            <input type="checkbox" name="c{{item.id}}" value="clicked">
                        {% endif %}
                    </div>
                </div>
                
                <input type="text" class="form-control" value="{{item.text}}">
            </div>
                
            {% endfor %}
            </div> 
        {% endfor %}
        
        
    </form>
    -->

templates/main/navbar.html
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
<style>
  a{
    font-size: large;
    padding-right: 3em;
  }
  .navbar-brand{
    font-family: 'Dancing Script', cursive;
    font-size: 2em;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="navbar-header border border-warning">
    <a class="navbar-brand text-white" href="{% url 'main:home'%}">MySite</a>
  </div>
  <div class="col-sm-4 text-center justify-content-center border border-info">
    <span class="text-white h5 mr-auto">Hello, {{ user.username|default:'Guest' }}! </span>
  </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    
  
  <div class="collapse navbar-collapse mr-5" id="navbarTogglerDemo02">
    
    <ul class="navbar-nav mt-2 mt-lg-0 ml-auto ">
      <li class="nav-item active px-3">
        <a class="nav-link text-white" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>  
    
    {% if user.is_authenticated %}
    <!-- <ul class="navbar-nav mt-2 mt-lg-0 ml-auto "> -->
      <li class="nav-item px-3">
        <a class="nav-link text-white" href="{% url 'main:create' %}">Create</a>
      </li>
      
      <li class="nav-item px-3 ">              
        <a class="nav-link text-white" href="{% url 'main:mylist'%}">Lists</a>
      </li>
      <li class="nav-item active px-3">
        <a class="nav-link text-white" href="{% url 'logout' %}">Logout</a>
      </li>
      <li class="nav-item active px-3">
          <a class="nav-link text-white" href="#">Profile</a>
      </li>
      {% else %}
      <li class="nav-item active px-3">
        <a class="nav-link text-white" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %}
    </ul> 
     
  </div>
  
</nav>

templates/main/todolist_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

templates/main/todolist_form.html
{% extends 'main/home.html' %}

{% block content %}
        <div class="card  border border-info">

            <div class="card-header bg-info text-center p-2 text-white">
                <h3> Create New List</h3>
            </div>

            <div class="card-body">
                
                <form action="" method="post" class="form-horizontal" enctype="multipart/form-data">                    
                    {% csrf_token %}
                    <div class="row border border-primary justify-content-center">
                        <div class="col-sm-6 border border-danger p-2 m-2">
                            {{form.as_p}}
                        </div>
                        
                    </div>
                    
                    <!-- {% include 'main/form_template.html' %} -->

                    <div class="form-group mb-3 px-5">                            
                        <button type="submit" name="save" class="btn btn-lg btn-info btn-block">Submit</button>                                
                    </div>                        
                </form>

            </div>
    
        </div>
    
    

{% endblock %}